function expProfit = expectedProfit(topPercent, ...
                              bottomPercent, precision, recall)

expProfit = (topPercent * precision) - ...
                      (bottomPercent * (1 - precision));
endfunction
