function profit = profitPerDay(posNum, actualPosNum,...
                                  dealsPerDay, expectedProfit)
  profit = ...
    (1 + expectedProfit) ^ ...
      (dealsPerDay * (posNum / actualPosNum)) - 1;

endfunction
